name: Gmail to Calendar Daily

on:
  schedule:
    # Setting to midnight UTC, to see when it runs
    - cron: '0 0 * * *'  # Note: Perth is +8 from UTC,
  workflow_dispatch:       # Optional: allows manual runs from GitHub UI

env:
  GMAIL_API_TOKEN_BASE64: ${{ secrets.GMAIL_API_TOKEN_BASE64 }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  CALENDAR_ID: ${{ secrets.CALENDAR_ID }}

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Choose your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python main.py
